version: "3.8"

services:
  #frontend:
  #  image: myapp-frontend:latest
  #  build:
  #    context: ./frontend
  #    dockerfile: Dockerfile
  #  ports:
  #    - "4200:4200"
  #  depends_on:
  #    - api-gateway  

  backend:
    image: backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7021:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=sqlserver,1433;Initial Catalog=ProductTrack;Persist Security Info=True;TrustServerCertificate=True; User ID=SA;Password=logPaSs#123$32
    depends_on:
      - sqlserver
      - smtp-notifications

  serv-usuario:
    image: serv-usuario:latest
    build:
      context: ./Serv-usuarios
      dockerfile: Dockerfile
    ports:
      - "7022:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=sqlserver,1433;Initial Catalog=ProductTrack;Persist Security Info=True;TrustServerCertificate=True; User ID=SA;Password=logPaSs#123$32
    depends_on:
      - sqlserver
      - smtp-notifications      
       

  serv-negocio:
    image: serv-negocio:latest
    build:
      context: ./Serv-negocio
      dockerfile: Dockerfile
    ports:
      - "7020:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=sqlserver,1433;Initial Catalog=ProductTrack;Persist Security Info=True;TrustServerCertificate=True; User ID=SA;Password=logPaSs#123$32 
    depends_on:
      - sqlserver  
      - smtp-notifications 

  api-gateway:
    image: api-gateway:latest 
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile
    ports: 
      - "3000:3000" 
    depends_on:
      - backend
      - serv-negocio 
      - serv-usuario     
    # environment:
    #   - NODE_TLS_REJECT_UNAUTHORIZED=0 

  smtp-notifications:
    image: smtp:latest
    build:
      context: ./smtp
      dockerfile: Dockerfile
    ports:
      - "3001:3000"  # Cambia el puerto si tu aplicación usa uno diferente
    # depends_on:
      
      

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=logPaSs#123$32
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql    
    restart: always     

volumes:
  sql_data:
    driver: local
