version: "3.8"

services:
  #frontend:
  #  image: myapp-frontend:latest
  #  build:
  #    context: ./frontend
  #    dockerfile: Dockerfile
  #  ports:
  #    - "4200:4200"
  #  depends_on:
  #    - api-gateway  

  backend:
    image: backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7022:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=ProductTrack.mssql.somee.com;Initial Catalog=ProductTrack;Persist Security Info=True;User ID=fleetRutePro_SQLLogin_1;Password=amlqpd88qw;TrustServerCertificate=True

  serv-negocio:
    image: serv-negocio:latest
    build:
      context: ./Serv-negocio
      dockerfile: Dockerfile
    ports:
      - "7020:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=ProductTrack.mssql.somee.com;Initial Catalog=ProductTrack;Persist Security Info=True;User ID=fleetRutePro_SQLLogin_1;Password=amlqpd88qw;TrustServerCertificate=True  

  api-gateway:
    image: api-gateway:latest 
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile
    ports: 
    - "3000:3000" 
    depends_on:
      - backend
      - serv-negocio
    #environment:
    #-NODE_TLS_REJECT_UNAUTHORIZED=0 


