version: "3.8"

services:

  frontend:
    image: myapp-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - backend 

  backend:
    image: backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=ProductTrack.mssql.somee.com;Initial Catalog=ProductTrack;Persist Security Info=True;User ID=fleetRutePro_SQLLogin_1;Password=amlqpd88qw;TrustServerCertificate=True  
    

